### ISSUE TITLE
[Tracking Issue] TS v3 Docs Updates

### ISSUE THREAD

**Issue by malgamves** [weaviate/weaviate-io#2124]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### What part of document/web-page on weaviate.io is affected?

Developer [Documentation](https://weaviate.io/developers/weaviate/starter-guides/connect) part of the website. 

Here are items I will work on.

#### Need content
- [x] Quickstart 
- [x] Connect to Weaviate 
- [x] Embedded Weaviate
- [x] How to configure Weaviate (update mention of `vectorizer`)
  - [ ] Product Quantization (compression)
  - [ ] Binary Quantization (compression)
- [ ] Manage collections

#### Need review and correction
- [ ] Schema (collection definitions)

### Additional comments?

Nope.

**Comment by daveatweaviate** [comment]
@malgamves  - what is focus of this issue? I'm not sure what the expectation is.

**Comment by daveatweaviate** [comment]
@Ayush9026 Thanks for your interest in working with Weaviate. Unfortunately, we're closing this issue since the work has been already been done as part of other projects.
